export const GET_TABLE_REQUEST = 'GET_TABLE_REQUEST';
export const GET_TABLE_SUCCESS = 'GET_TABLE_SUCCESS';
export const GET_TABLE_FAILURE = 'GET_TABLE_FAILURE';

export const CREATE_LINK_REQUEST = 'CREATE_LINK_REQUEST';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_FAILURE = 'CREATE_LINK_FAILURE';

export const CREATE_LINK_AUTH_REQUEST = 'CREATE_LINK_AUTH_REQUEST';
export const CREATE_LINK_AUTH_SUCCESS = 'CREATE_LINK_AUTH_SUCCESS';
export const CREATE_LINK_AUTH_FAILURE = 'CREATE_LINK_AUTH_FAILURE';

export const REMOVE_LINK_REQUEST = 'REMOVE_LINK_REQUEST';
export const REMOVE_LINK_SUCCESS = 'REMOVE_LINK_SUCCESS';
export const REMOVE_LINK_FAILURE = 'REMOVE_LINK_FAILURE';

